/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ListAccountsResponseLinks } from './listAccountsResponseLinks';
import { WebhookDeliveryLogResource } from './webhookDeliveryLogResource';

/**
* Successful response to get all delivery logs for a webhook. This returns a [paginated](#pagination) list of delivery logs, which can be scrolled by following the `next` and `prev` links if present. 
*/
export class ListWebhookDeliveryLogsResponse {
    /**
    * The list of delivery logs returned in this response. 
    */
    'data': Array<WebhookDeliveryLogResource>;
    'links': ListAccountsResponseLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<WebhookDeliveryLogResource>"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ListAccountsResponseLinks"
        }    ];

    static getAttributeTypeMap() {
        return ListWebhookDeliveryLogsResponse.attributeTypeMap;
    }
}

