/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ListAccountsResponseLinks {
    /**
    * The link to the previous page in the results. If this value is `null` there is no previous page. 
    */
    'prev': string | null;
    /**
    * The link to the next page in the results. If this value is `null` there is no next page. 
    */
    'next': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "prev",
            "baseName": "prev",
            "type": "string"
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListAccountsResponseLinks.attributeTypeMap;
    }
}

