/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { MoneyObject } from './moneyObject';

/**
* Provides information about how a Round Up was applied, such as whether or not a boost was included in the Round Up. 
*/
export class RoundUpObject {
    /**
    * The total amount of this Round Up, represented as negative value. 
    */
    'amount': MoneyObject;
    /**
    * The portion of the Round Up `amount` owing to boosted Round Ups, represented as a negative value. If no boost was added to the Round Up this field will be `null`. 
    */
    'boostPortion': MoneyObject | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "MoneyObject"
        },
        {
            "name": "boostPortion",
            "baseName": "boostPortion",
            "type": "MoneyObject"
        }    ];

    static getAttributeTypeMap() {
        return RoundUpObject.attributeTypeMap;
    }
}

