/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CashbackObject } from './cashbackObject';
import { HoldInfoObject } from './holdInfoObject';
import { MoneyObject } from './moneyObject';
import { RoundUpObject } from './roundUpObject';
import { TransactionStatusEnum } from './transactionStatusEnum';

export class TransactionResourceAttributes {
    /**
    * The current processing status of this transaction, according to whether or not this transaction has settled or is still held. 
    */
    'status': TransactionStatusEnum;
    /**
    * The original, unprocessed text of the transaction. This is often not a perfect indicator of the actual merchant, but it is useful for reconciliation purposes in some cases. 
    */
    'rawText': string | null;
    /**
    * A short description for this transaction. Usually the merchant name for purchases. 
    */
    'description': string;
    /**
    * Attached message for this transaction, such as a payment message, or a transfer note. 
    */
    'message': string | null;
    /**
    * If this transaction is currently in the `HELD` status, or was ever in the `HELD` status, the `amount` and `foreignAmount` of the transaction while `HELD`. 
    */
    'holdInfo': HoldInfoObject | null;
    /**
    * Details of how this transaction was rounded-up. If no Round Up was applied this field will be `null`. 
    */
    'roundUp': RoundUpObject | null;
    /**
    * If all or part of this transaction was instantly reimbursed in the form of cashback, details of the reimbursement. 
    */
    'cashback': CashbackObject | null;
    /**
    * The amount of this transaction in Australian dollars. For transactions that were once `HELD` but are now `SETTLED`, refer to the `holdInfo` field for the original `amount` the transaction was `HELD` at. 
    */
    'amount': MoneyObject;
    /**
    * The foreign currency amount of this transaction. This field will be `null` for domestic transactions. The amount was converted to the AUD amount reflected in the `amount` of this transaction. Refer to the `holdInfo` field for the original `foreignAmount` the transaction was `HELD` at. 
    */
    'foreignAmount': MoneyObject | null;
    /**
    * The date-time at which this transaction settled. This field will be `null` for transactions that are currently in the `HELD` status. 
    */
    'settledAt': Date | null;
    /**
    * The date-time at which this transaction was first encountered. 
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "TransactionStatusEnum"
        },
        {
            "name": "rawText",
            "baseName": "rawText",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "holdInfo",
            "baseName": "holdInfo",
            "type": "HoldInfoObject"
        },
        {
            "name": "roundUp",
            "baseName": "roundUp",
            "type": "RoundUpObject"
        },
        {
            "name": "cashback",
            "baseName": "cashback",
            "type": "CashbackObject"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "MoneyObject"
        },
        {
            "name": "foreignAmount",
            "baseName": "foreignAmount",
            "type": "MoneyObject"
        },
        {
            "name": "settledAt",
            "baseName": "settledAt",
            "type": "Date"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return TransactionResourceAttributes.attributeTypeMap;
    }
}

