/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { WebhookDeliveryLogResourceAttributesRequest } from './webhookDeliveryLogResourceAttributesRequest';
import { WebhookDeliveryLogResourceAttributesResponse } from './webhookDeliveryLogResourceAttributesResponse';
import { WebhookDeliveryStatusEnum } from './webhookDeliveryStatusEnum';

export class WebhookDeliveryLogResourceAttributes {
    'request': WebhookDeliveryLogResourceAttributesRequest;
    'response': WebhookDeliveryLogResourceAttributesResponse | null;
    /**
    * The success or failure status of this delivery attempt. 
    */
    'deliveryStatus': WebhookDeliveryStatusEnum;
    /**
    * The date-time at which this log entry was created. 
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "request",
            "baseName": "request",
            "type": "WebhookDeliveryLogResourceAttributesRequest"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "WebhookDeliveryLogResourceAttributesResponse"
        },
        {
            "name": "deliveryStatus",
            "baseName": "deliveryStatus",
            "type": "WebhookDeliveryStatusEnum"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return WebhookDeliveryLogResourceAttributes.attributeTypeMap;
    }
}

